### ISSUE TITLE
Please provide dependencies (POM file, lib dir with jars)

### ISSUE THREAD

**Issue by OliverHrdz** [bluejoe2008/elfinder-2.x-servlet#1]
Cannot build the source in the download as there are 3rd party dependencies not specified anywhere.  It would be more convenient if the download includes a working Maven POM file.

**Comment by bluejoe2008** [comment]
jars are included in lib directory
sorry for not using Maven to manage dependecies

**Comment by OliverHrdz** [comment]
Ahh, I didn't think to look in the compiled WEB-INF/lib directory, that helps!  I can contribute a POM file once I get it working, thanks!

**Comment by buckett** [comment]
BTW I think this got fixed with #3 so you should be able to use maven now.
