### ISSUE TITLE
Make maven artifact release

### ISSUE THREAD

**Issue by buckett** [bluejoe2008/elfinder-2.x-servlet#18]
For inclusion into the Sakai project it would be helpful if this project was released as a maven artifact so that Sakai builds could depend on it and download it, rather than including a copy of the elfinder code in the Sakai codebase.

The alternative is that we have a Sakai fork, which we release to the Sonatype repository.

Do you have any preferences?

**Comment by bluejoe2008** [comment]
i prefer the first way 
but what should i do now? i need to release this project to a public repository, right?

**Comment by bluejoe2008** [comment]
both ways are ok
you can also download this project and distribute it into local repository using
`mvn clean package install`
then add this artifact as a dependency in Sakai project
right?

**Comment by buckett** [comment]
There's documentation on how todo a release to the main OSS respository in: http://central.sonatype.org/pages/ossrh-guide.html

It might be worth switching development to the master branch and also consider the maven coordinates that are used (http://central.sonatype.org/pages/choosing-your-coordinates.html), at the moment it's using org.elfinder as the groupId and it's probably better to release under com.github.bluejoe2008 as that's easy for the Sonatype people to verify.

Generally Sakai doesn't pull in copies of other projects if they are available as dependencies in Maven and I'm not sure making it available as a submodule or code dump is a good long term solution.

**Comment by buckett** [comment]
I'm happy todo setup all the sonatype stuff, just wanted to run it by you.

**Comment by bluejoe2008** [comment]
yes
i agree with you about choosing more acceptable names for  packages and groupid

the package name ....bluejoe2008 still looks personal and private
but i have no better name now
i will

**Comment by bluejoe2008** [comment]
hi, bucket

i have released the artifact to central repository

use

```
<dependency>
    <groupId>com.github.bluejoe2008</groupId>
    <artifactId>elfinder-servlet-2</artifactId>
    <version>1.0</version>
</dependency>
```

to add dependency

**Comment by buckett** [comment]
Magic, thanks.

I noticed that the changes that makeup version 1.0 don't seem to be on github?

**Comment by buckett** [comment]
Also I can't see the classess classifier on http://search.maven.org/#artifactdetails%7Ccom.github.bluejoe2008%7Celfinder-servlet-2%7C1.0%7Cjar

**Comment by bluejoe2008** [comment]
eh... i updated the pom.xml file, it is just a little change.
while the change was not committed due to bad network connection. 

is the classifier tag necessary? i have no idea.
this artifact can run on JDK1.5~JDK1.7

**Comment by buckett** [comment]
In #6 I added support for generating a classes classifier which means that the java classes are built as a separate artifact. This allows extension project to the ability to get most of the code java code without the webapp files and the xml wiring.

**Comment by buckett** [comment]
My Sonatype username is `buckett` if you could ask for me to to be allowed to deploy artifacts I'll create a 1.1 release that includes the classes artifact.

**Comment by bluejoe2008** [comment]
great!
please help me to create such a release:)
what should i do? provides my sonatype username or?

**Comment by buckett** [comment]
If you tell sonatype you'd also like to allow me to release the artifacts they can grant me permission to make releases too.

It needs to be you that asks as you're the current owner of com.github.bluejoe2008
My Sonatype username is buckett

**Comment by bluejoe2008** [comment]
hi, buckett
i have sent the request to Sonatype and permissions were granted now.
see https://issues.sonatype.org/browse/OSSRH-17784

**Comment by buckett** [comment]
Thanks, I've made a release there (1.1) and I've updated the POM a little. I've also documented how I made the release using the maven release plugin, this tags, builds and deploys the artifacts.

**Comment by bluejoe2008** [comment]
many thanks!
i see the 'Making a release' section in README.
thank you!
