### ISSUE TITLE
IE Drop file(s) for upload does not work

### ISSUE THREAD

**Issue by LoneEagle70** [bluejoe2008/elfinder-2.x-servlet#22]
The Drop of file(s) for IE (11) does not work while Chrome does.

Class: UploadCommandExecutor.java

For the file droped: (ex. "C:\temp\abc.txt"):
    Chrome: fileName = "abc.txt"
    IE: fileName = "C:\temp\abc.txt"

Temporary fix: Always try to get only the filename.

```
    // OLD: String fileName = fis.getName();
    // OLD: FsItemEx newFile = new FsItemEx(dir, fileName);
    java.nio.file.Path p = java.nio.file.Paths.get(fis.getName());
    FsItemEx newFile = new FsItemEx(dir, p.getFileName().toString());
```

Note: Could it be fixed at higher level like javascript?

**Comment by bluejoe2008** [comment]
the server side code is updated following your suggestion.
