### ISSUE TITLE
目录/文件的修改时间显示不正常

### ISSUE THREAD

**Issue by itkf** [bluejoe2008/elfinder-2.x-servlet#46]
目录/文件的修改时间全部显示为“今天”
是否应该按照文档中修改：
https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1#information-about-filedirectory
"ts"     : 1334163643,           // (Number) file modification time in **unix timestamp**. Required.

**Comment by bluejoe2008** [comment]
you are right
thanks
