### ISSUE TITLE
No server side filtering by mime type

### ISSUE THREAD

**Issue by lokothodida** [bluejoe2008/elfinder-2.x-servlet#8]
There is a client-side option in elFinder that allows one to [filter the results by mime](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#onlyMimes):

``` javascript
{
  // ...
  // Restrict to images and flash files
  onlyMimes: ['image', 'application/x-shockwave-flash']
  // ...
}
```

Each option in the `onlyMimes` array is sent on the server-side URL requests, e.g:

```
?mimes[]=image&mimes[]=application%2Fx-shockwave-flash&cmd=open&target=SOMEHASH&init=1&tree=1
```

This servlet doesn't yet support the client-side filtering (i.e. no matter what you give to the `onlyMimes` array, all files are returned in response JSONs).

The [exec](https://github.com/Studio-42/elFinder/blob/2.1/php/elFinder.class.php#L474) command in the `elFinder` PHP class seems to take the `mimes` array and set the filter. Not sure where this would need to be implemented in the Java servlet.

**Comment by buckett** [comment]
Is `onlyMimes` only supported by version 2.1?
What commands is it sent with, I'd imaging it's the `ls` command.

**Comment by bluejoe2008** [comment]
this bug is fixed now
see also https://github.com/bluejoe2008/elfinder-2.x-servlet/commit/058bd4c8b2e97c74bd8814b6edd851ad0568d5ca
OpenCommand, LsCommand and MkfileCommand are updated

**Comment by buckett** [comment]
Magic, thanks.

On 14 August 2015 at 15:35, shen zhihong notifications@github.com wrote:

> this bug is fixed now
> OpenCommand, LsCommand and MkfileCommand
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bluejoe2008/elfinder-2.x-servlet/issues/8#issuecomment-131126528
> .

## 

  Matthew Buckett
